"""
Rich, realistic seed dataset of road hazards across diverse defects, locations, traffic levels,
proximity to schools/hospitals, and historical measurements.
Scores are computed DYNAMICALLY via the scoring engine (never hard-coded).
"""
import uuid
from datetime import datetime, timedelta
from typing import List
from app.models.road_hazard_models import RoadHazard, TrafficDensity, MaintenanceStatus, HistoricalObservation
from app.services.scoring_engine import scoring_engine


RAW_SEED_HAZARDS = [
    {
        "hazardId": "RH-1024",
        "defectType": "Large Pothole",
        "confidence": 0.94,
        "latitude": 13.0827,
        "longitude": 80.2155,
        "locationName": "Anna Nagar 2nd Avenue, near Roundtana",
        "roadSegment": "Anna Nagar Main Road",
        "estimatedLengthCm": 85.0,
        "estimatedWidthCm": 70.0,
        "sizeCategory": "Very large",
        "trafficDensity": TrafficDensity.VERY_HIGH,
        "trafficSource": "Simulated (Urban Arterial Peak)",
        "vulnerableAreaType": "School",
        "vulnerableAreaDistanceM": 65.0,
        "detectionCount": 9,
        "firstDetected": (datetime.now() - timedelta(days=21)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.ASSIGNED,
        "assignedTeam": "Zone 8 Pavement Crew",
        "history": [
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=21)).strftime("%Y-%m-%d"), sizeEstimateMm=450, severityScore=71.0, confidence=0.89),
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=14)).strftime("%Y-%m-%d"), sizeEstimateMm=580, severityScore=76.0, confidence=0.91),
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d"), sizeEstimateMm=720, severityScore=82.0, confidence=0.93),
            HistoricalObservation(timestamp=datetime.now().strftime("%Y-%m-%d"), sizeEstimateMm=850, severityScore=88.0, confidence=0.94),
        ],
        "notes": "Severe depth (~12cm). Deep impact hazard for two-wheelers and buses.",
        "imageUrl": "/static/images/pothole_large.jpg"
    },
    {
        "hazardId": "RH-1025",
        "defectType": "Road Collapse",
        "confidence": 0.97,
        "latitude": 13.0610,
        "longitude": 80.2435,
        "locationName": "Mount Road / Anna Salai, Thousand Lights Junction",
        "roadSegment": "Anna Salai Corridor",
        "estimatedLengthCm": 140.0,
        "estimatedWidthCm": 110.0,
        "sizeCategory": "Very large",
        "trafficDensity": TrafficDensity.VERY_HIGH,
        "trafficSource": "Simulated (Major Metro Trunk)",
        "vulnerableAreaType": "Metro / Pedestrian Crossing",
        "vulnerableAreaDistanceM": 40.0,
        "detectionCount": 7,
        "firstDetected": (datetime.now() - timedelta(days=5)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.IN_PROGRESS,
        "assignedTeam": "Metro Emergency Civil Ops",
        "history": [
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=5)).strftime("%Y-%m-%d"), sizeEstimateMm=900, severityScore=86.0, confidence=0.95),
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=2)).strftime("%Y-%m-%d"), sizeEstimateMm=1200, severityScore=91.0, confidence=0.96),
            HistoricalObservation(timestamp=datetime.now().strftime("%Y-%m-%d"), sizeEstimateMm=1400, severityScore=94.0, confidence=0.97),
        ],
        "notes": "Sub-base subsidence after heavy storm pipe seepage. Structural risk.",
        "imageUrl": "/static/images/road_collapse.jpg"
    },
    {
        "hazardId": "RH-1026",
        "defectType": "Exposed/Damaged Manhole",
        "confidence": 0.91,
        "latitude": 12.9815,
        "longitude": 80.2180,
        "locationName": "GST Road, Guindy Flyover Underpass",
        "roadSegment": "GST Road",
        "estimatedLengthCm": 60.0,
        "estimatedWidthCm": 60.0,
        "sizeCategory": "Medium",
        "trafficDensity": TrafficDensity.VERY_HIGH,
        "trafficSource": "Simulated (Highway Link)",
        "vulnerableAreaType": "Bus Stop",
        "vulnerableAreaDistanceM": 30.0,
        "detectionCount": 8,
        "firstDetected": (datetime.now() - timedelta(days=12)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.DETECTED,
        "assignedTeam": None,
        "history": [
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=12)).strftime("%Y-%m-%d"), sizeEstimateMm=600, severityScore=78.0, confidence=0.88),
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=4)).strftime("%Y-%m-%d"), sizeEstimateMm=600, severityScore=81.0, confidence=0.91),
        ],
        "notes": "Manhole cover displaced by ~7cm, steel rim exposed.",
        "imageUrl": "/static/images/manhole.jpg"
    },
    {
        "hazardId": "RH-1027",
        "defectType": "Waterlogging",
        "confidence": 0.88,
        "latitude": 12.9750,
        "longitude": 80.2205,
        "locationName": "Velachery Main Road, near Vijayanagar Junction",
        "roadSegment": "Velachery Arterial",
        "estimatedLengthCm": 320.0,
        "estimatedWidthCm": 180.0,
        "sizeCategory": "Very large",
        "trafficDensity": TrafficDensity.HIGH,
        "trafficSource": "Simulated",
        "vulnerableAreaType": "Hospital",
        "vulnerableAreaDistanceM": 90.0,
        "detectionCount": 5,
        "firstDetected": (datetime.now() - timedelta(days=4)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.VERIFIED,
        "assignedTeam": None,
        "history": [
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=4)).strftime("%Y-%m-%d"), sizeEstimateMm=2000, severityScore=68.0, confidence=0.85),
            HistoricalObservation(timestamp=datetime.now().strftime("%Y-%m-%d"), sizeEstimateMm=3200, severityScore=74.0, confidence=0.88),
        ],
        "notes": "Standing stormwater ~15cm deep blocking left lane access to clinic.",
        "imageUrl": "/static/images/waterlogging.jpg"
    },
    {
        "hazardId": "RH-1028",
        "defectType": "Damaged Speed Breaker",
        "confidence": 0.89,
        "latitude": 13.0382,
        "longitude": 80.2135,
        "locationName": "K.K. Nagar 8th Sector, Ashok Nagar Link",
        "roadSegment": "Ashok Nagar Cross",
        "estimatedLengthCm": 210.0,
        "estimatedWidthCm": 45.0,
        "sizeCategory": "Large",
        "trafficDensity": TrafficDensity.HIGH,
        "trafficSource": "Simulated",
        "vulnerableAreaType": "School",
        "vulnerableAreaDistanceM": 45.0,
        "detectionCount": 6,
        "firstDetected": (datetime.now() - timedelta(days=10)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.ASSIGNED,
        "assignedTeam": "Zone 10 Road Safety",
        "history": [
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=10)).strftime("%Y-%m-%d"), sizeEstimateMm=1500, severityScore=67.0, confidence=0.84),
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=3)).strftime("%Y-%m-%d"), sizeEstimateMm=2100, severityScore=73.0, confidence=0.89),
        ],
        "notes": "Asphalt mound chipped with sharp exposed foundation rebar.",
        "imageUrl": "/static/images/speed_breaker.jpg"
    },
    {
        "hazardId": "RH-1029",
        "defectType": "Pothole",
        "confidence": 0.92,
        "latitude": 13.0425,
        "longitude": 80.2580,
        "locationName": "Cathedral Road, near Stella Maris College",
        "roadSegment": "Cathedral Road",
        "estimatedLengthCm": 45.0,
        "estimatedWidthCm": 40.0,
        "sizeCategory": "Medium",
        "trafficDensity": TrafficDensity.HIGH,
        "trafficSource": "Simulated",
        "vulnerableAreaType": "College",
        "vulnerableAreaDistanceM": 85.0,
        "detectionCount": 4,
        "firstDetected": (datetime.now() - timedelta(days=8)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.VERIFIED,
        "assignedTeam": None,
        "history": [
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=8)).strftime("%Y-%m-%d"), sizeEstimateMm=350, severityScore=56.0, confidence=0.88),
            HistoricalObservation(timestamp=datetime.now().strftime("%Y-%m-%d"), sizeEstimateMm=450, severityScore=61.0, confidence=0.92),
        ],
        "notes": "Bowl-shaped pothole developing on center lane.",
        "imageUrl": "/static/images/pothole_medium.jpg"
    },
    {
        "hazardId": "RH-1030",
        "defectType": "Road Depression",
        "confidence": 0.85,
        "latitude": 13.0035,
        "longitude": 80.2010,
        "locationName": "Kathipara Link, Alandur Junction",
        "roadSegment": "GST Road",
        "estimatedLengthCm": 90.0,
        "estimatedWidthCm": 75.0,
        "sizeCategory": "Medium",
        "trafficDensity": TrafficDensity.HIGH,
        "trafficSource": "Simulated",
        "vulnerableAreaType": "Railway Station",
        "vulnerableAreaDistanceM": 120.0,
        "detectionCount": 3,
        "firstDetected": (datetime.now() - timedelta(days=14)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.DETECTED,
        "assignedTeam": None,
        "history": [
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=14)).strftime("%Y-%m-%d"), sizeEstimateMm=700, severityScore=48.0, confidence=0.81),
            HistoricalObservation(timestamp=datetime.now().strftime("%Y-%m-%d"), sizeEstimateMm=900, severityScore=53.0, confidence=0.85),
        ],
        "notes": "Surface undulation causing sudden vehicle lurch at 40km/h.",
        "imageUrl": "/static/images/depression.jpg"
    },
    {
        "hazardId": "RH-1031",
        "defectType": "Surface Crack",
        "confidence": 0.90,
        "latitude": 13.0880,
        "longitude": 80.2750,
        "locationName": "Poonamallee High Road, near Chennai Central",
        "roadSegment": "Poonamallee High Road",
        "estimatedLengthCm": 110.0,
        "estimatedWidthCm": 8.0,
        "sizeCategory": "Medium",
        "trafficDensity": TrafficDensity.HIGH,
        "trafficSource": "Simulated",
        "vulnerableAreaType": "Railway Station",
        "vulnerableAreaDistanceM": 110.0,
        "detectionCount": 3,
        "firstDetected": (datetime.now() - timedelta(days=7)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.DETECTED,
        "assignedTeam": None,
        "history": [
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d"), sizeEstimateMm=800, severityScore=38.0, confidence=0.87),
            HistoricalObservation(timestamp=datetime.now().strftime("%Y-%m-%d"), sizeEstimateMm=1100, severityScore=42.0, confidence=0.90),
        ],
        "notes": "Longitudinal surface fissure extending across outer lane.",
        "imageUrl": "/static/images/crack_surface.jpg"
    },
    {
        "hazardId": "RH-1032",
        "defectType": "Minor Crack",
        "confidence": 0.83,
        "latitude": 13.0210,
        "longitude": 80.2240,
        "locationName": "Gandhi Nagar 3rd Cross Road, Adyar",
        "roadSegment": "Adyar Residential Sector",
        "estimatedLengthCm": 35.0,
        "estimatedWidthCm": 3.0,
        "sizeCategory": "Small",
        "trafficDensity": TrafficDensity.LOW,
        "trafficSource": "Simulated",
        "vulnerableAreaType": "Residential Zone",
        "vulnerableAreaDistanceM": 290.0,
        "detectionCount": 1,
        "firstDetected": datetime.now().isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.DETECTED,
        "assignedTeam": None,
        "history": [],
        "notes": "Hairline crack on quiet residential street.",
        "imageUrl": "/static/images/crack_minor.jpg"
    },
    {
        "hazardId": "RH-1033",
        "defectType": "Pothole",
        "confidence": 0.87,
        "latitude": 13.0720,
        "longitude": 80.2610,
        "locationName": "Pantheon Road, Egmore Museum Gate",
        "roadSegment": "Pantheon Road",
        "estimatedLengthCm": 50.0,
        "estimatedWidthCm": 45.0,
        "sizeCategory": "Medium",
        "trafficDensity": TrafficDensity.MODERATE,
        "trafficSource": "Simulated",
        "vulnerableAreaType": "Pedestrian Crossing",
        "vulnerableAreaDistanceM": 75.0,
        "detectionCount": 4,
        "firstDetected": (datetime.now() - timedelta(days=16)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.VERIFIED,
        "assignedTeam": None,
        "history": [
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=16)).strftime("%Y-%m-%d"), sizeEstimateMm=400, severityScore=52.0, confidence=0.82),
            HistoricalObservation(timestamp=datetime.now().strftime("%Y-%m-%d"), sizeEstimateMm=500, severityScore=58.0, confidence=0.87),
        ],
        "notes": "Moderate pothole directly adjacent to pedestrian zebra crossing.",
        "imageUrl": "/static/images/pothole_medium.jpg"
    },
    {
        "hazardId": "RH-1034",
        "defectType": "Surface Crack",
        "confidence": 0.86,
        "latitude": 12.9230,
        "longitude": 80.1420,
        "locationName": "Tambaram Sanatorium Ring Road",
        "roadSegment": "GST Road",
        "estimatedLengthCm": 65.0,
        "estimatedWidthCm": 5.0,
        "sizeCategory": "Small",
        "trafficDensity": TrafficDensity.MODERATE,
        "trafficSource": "Simulated",
        "vulnerableAreaType": "Hospital",
        "vulnerableAreaDistanceM": 210.0,
        "detectionCount": 2,
        "firstDetected": (datetime.now() - timedelta(days=9)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.DETECTED,
        "assignedTeam": None,
        "history": [],
        "notes": "Alligator cracking pattern beginning to form.",
        "imageUrl": "/static/images/crack_surface.jpg"
    },
    {
        "hazardId": "RH-1035",
        "defectType": "Pothole",
        "confidence": 0.95,
        "latitude": 13.0875,
        "longitude": 80.2090,
        "locationName": "Anna Nagar West Extension, Bus Terminus road",
        "roadSegment": "Anna Nagar Main Road",
        "estimatedLengthCm": 75.0,
        "estimatedWidthCm": 65.0,
        "sizeCategory": "Large",
        "trafficDensity": TrafficDensity.HIGH,
        "trafficSource": "Simulated",
        "vulnerableAreaType": "Bus Stop",
        "vulnerableAreaDistanceM": 55.0,
        "detectionCount": 7,
        "firstDetected": (datetime.now() - timedelta(days=15)).isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.ASSIGNED,
        "assignedTeam": "Zone 8 Road Crew",
        "history": [
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=15)).strftime("%Y-%m-%d"), sizeEstimateMm=500, severityScore=64.0, confidence=0.88),
            HistoricalObservation(timestamp=(datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d"), sizeEstimateMm=650, severityScore=72.0, confidence=0.92),
            HistoricalObservation(timestamp=datetime.now().strftime("%Y-%m-%d"), sizeEstimateMm=750, severityScore=77.0, confidence=0.95),
        ],
        "notes": "High frequency pothole on busy transit lane.",
        "imageUrl": "/static/images/pothole_large.jpg"
    },
    {
        "hazardId": "RH-1036",
        "defectType": "Minor Crack",
        "confidence": 0.81,
        "latitude": 13.0350,
        "longitude": 80.2710,
        "locationName": "Besant Avenue, near Theosophical Society",
        "roadSegment": "Besant Nagar Greenways",
        "estimatedLengthCm": 25.0,
        "estimatedWidthCm": 2.0,
        "sizeCategory": "Very small",
        "trafficDensity": TrafficDensity.LOW,
        "trafficSource": "Simulated",
        "vulnerableAreaType": None,
        "vulnerableAreaDistanceM": None,
        "detectionCount": 1,
        "firstDetected": datetime.now().isoformat(),
        "lastDetected": datetime.now().isoformat(),
        "maintenanceStatus": MaintenanceStatus.RESOLVED,
        "assignedTeam": "Ward 174 Maintenance",
        "history": [],
        "notes": "Sealed with polymer bitumen slurry. Hazard marked resolved.",
        "imageUrl": "/static/images/crack_minor.jpg"
    }
]

def generate_initial_hazards() -> List[RoadHazard]:
    hazards = []
    for item in RAW_SEED_HAZARDS:
        # Build feature vector to calculate real dynamic score
        feature_vector = {
            "defect_type": item["defectType"],
            "size_category": item["sizeCategory"],
            "bounding_box_area_ratio": None,
            "traffic_density": item["trafficDensity"].value,
            "vulnerable_area_distance_m": item["vulnerableAreaDistanceM"],
            "vulnerable_area_type": item["vulnerableAreaType"],
            "detection_count": item["detectionCount"],
            "history": item["history"]
        }

        # Dynamically compute severity, priority, breakdown, reasoning, and predictions
        score, priority, breakdown, reasoning, action, future_pred = scoring_engine.calculate(feature_vector)

        hazard = RoadHazard(
            hazardId=item["hazardId"],
            defectType=item["defectType"],
            confidence=item["confidence"],
            latitude=item["latitude"],
            longitude=item["longitude"],
            locationName=item["locationName"],
            roadSegment=item["roadSegment"],
            estimatedLengthCm=item["estimatedLengthCm"],
            estimatedWidthCm=item["estimatedWidthCm"],
            sizeCategory=item["sizeCategory"],
            trafficDensity=item["trafficDensity"],
            trafficSource=item["trafficSource"],
            vulnerableAreaType=item["vulnerableAreaType"],
            vulnerableAreaDistanceM=item["vulnerableAreaDistanceM"],
            detectionCount=item["detectionCount"],
            firstDetected=item["firstDetected"],
            lastDetected=item["lastDetected"],
            history=item["history"],
            severityScore=score,
            priorityLevel=priority,
            scoreBreakdown=breakdown,
            aiReasoning=reasoning,
            recommendedAction=action,
            maintenanceStatus=item["maintenanceStatus"],
            assignedTeam=item["assignedTeam"],
            notes=item["notes"],
            imageUrl=item["imageUrl"],
            futurePrediction=future_pred,
            created_at=item["firstDetected"],
            updated_at=item["lastDetected"]
        )
        hazards.append(hazard)
    return hazards
